/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lfp_practica1;


import javax.swing.JOptionPane;
import static lfp_practica1.Pantalla_Principal.T_texto;


/**
 *
 * @author Javier
 */
public class Recuentos extends javax.swing.JFrame {
String palabras;
public String [] cuento;   
    
    
    
    public Recuentos() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Recuento de Palabras");
        setSize(250, 440);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtrecuento = new javax.swing.JTextArea();
        jbMostrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(190, 220));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recuento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 20, 130, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Componentes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 70, 90, 17);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recuento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 70, 60, 17);

        jtrecuento.setColumns(20);
        jtrecuento.setRows(5);
        jtrecuento.setKeymap(null);
        jScrollPane2.setViewportView(jtrecuento);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 100, 190, 260);

        jbMostrar.setText("Mostrar");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbMostrar);
        jbMostrar.setBounds(130, 370, 90, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 70, 17, 14);

        jButton1.setText("Mas repetido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 370, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ECB.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -360, 550, 1600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
String [] palabras=Pantalla_Principal.T_texto.getText().split("\\s");
String buscar = Pantalla_Principal.T_texto.getText();
String [] pal =T_texto.getText().split(" ");


String p="";
String  a;
int contador=0;


for (int i=0; i<palabras.length;i++) {
   p= i+1 +" " +" "+ palabras[i]+ " \n ";
   a= palabras [i];
   System.out.println(palabras[i]);
         
                             String t = palabras[i];
                             String [] pala = t.split(" ");
                             int canti = pala.length;
         
            
                
    jtrecuento.setText(jtrecuento.getText()+ "" +canti + " ------------ " +p +"-----");
        }

    }//GEN-LAST:event_jbMostrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String cadena=T_texto.getText();
        char charCadena='\n';
        int[] resul = new int[300];
        int numeroVeces=0, letraRepetida=0;
      
        //suma un punto cada vez que se repite.
        for(int i=0;i<cadena.length();i++)           
           resul[cadena.codePointAt(i)]++;
        
       //busca el que tiene mas punto
        for(int i=48;i<resul.length;i++){
            if(resul[i]>=numeroVeces){                
                numeroVeces=resul[i];
                letraRepetida=i;
             }}
       
       //busca en la cadena original. 
        for(int i=0;i<cadena.length();i++){
            if (letraRepetida==cadena.codePointAt(i)){
                charCadena=cadena.charAt(i);                
            }
           
       }
   System.out.println("\nEl caracter mas repitdo es = "+charCadena);
   System.out.println("y se repite "+numeroVeces+" veces");
            
   
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recuentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbMostrar;
    public static javax.swing.JTextArea jtrecuento;
    // End of variables declaration//GEN-END:variables
}
